language: php
php:
    - 5.4
before_script:
    - composer install
    - sh -e /etc/init.d/xvfb start
    - export DISPLAY=:99.0
    - wget http://selenium.googlecode.com/files/selenium-server-standalone-2.31.0.jar
    - "java -jar selenium-server-standalone-2.31.0.jar > /dev/null &"
    - sleep 5
script:
    - vendor/bin/behat
